// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bug': string;
  'fire': string;
  'flying': string;
  'grass': string;
  'infoWrap': string;
  'label': string;
  'labelWrap': string;
  'pictureWrap': string;
  'poison': string;
  'root': string;
  'statItem': string;
  'statValue': string;
  'statWrap': string;
  'titleName': string;
  'water': string;
}
export const cssExports: CssExports;
export default cssExports;
