// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footerEmoji': string;
  'footer__emoji': string;
}
export const cssExports: CssExports;
export default cssExports;
